# Generated by Django 5.0.6 on 2024-07-01 01:47

import apps.entities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='biograph',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='github',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='', upload_to=apps.entities.models.Student.upload_to),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.SlugField(default='None'),
            preserve_default=False,
        ),
    ]
