# Generated by Django 5.0.6 on 2024-07-01 03:38

import apps.entities.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_student_biograph_student_github_student_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='unit',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='entities.unitstudent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='github',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(null=True, upload_to=apps.entities.models.Student.upload_to),
        ),
        migrations.AlterField(
            model_name='student',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
