# Generated by Django 5.0.6 on 2024-06-28 02:29

import apps.courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(default='/', upload_to=apps.courses.models.Course.upload_to),
            preserve_default=False,
        ),
    ]
