# Generated by Django 5.0.6 on 2024-07-05 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_exam_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.exam'),
            preserve_default=False,
        ),
    ]
